import React, { useState } from 'react';
import { createPortal } from 'react-dom';
import {
  IconShield,
  IconCopy,
  IconPrinter,
  IconExternalLink,
  IconCheck,
  IconX,
} from './Icons.jsx';

export default function DossierModal({ topic, briefing, diffs = [], onClose }) {
  const [copyStatus, setCopyStatus] = useState('');

  if (!topic || !briefing) return null;

  const volatility = briefing.volatilityScore ?? (briefing.urgency === 'CRITICAL' ? 85 : briefing.urgency === 'MODERATE' ? 55 : 25);
  const urgency = briefing.urgency || (volatility >= 75 ? 'CRITICAL' : volatility >= 45 ? 'MODERATE' : 'ROUTINE');
  const nowStr = new Date().toLocaleString('en-US', {
    dateStyle: 'full',
    timeStyle: 'short',
  });

  function handlePrint() {
    window.print();
  }

  function generateMarkdown() {
    let md = `# EXECUTIVE INTELLIGENCE DOSSIER\n`;
    md += `**Subject:** ${topic.name}\n`;
    md += `**Category:** ${(topic.category || 'General Notice').toUpperCase()} | **Ref ID:** ${topic.id}\n`;
    md += `**Query:** \`${topic.query}\`\n`;
    md += `**Generated:** ${nowStr}\n`;
    md += `**Classification:** AUTONOMOUS VERIFIED RADAR (SERPAPI + GEMINI AI)\n\n`;
    md += `---\n\n`;

    md += `## 1. RADAR METRICS & URGENCY ASSESSMENT\n`;
    md += `- **Urgency Status:** ${urgency} ACTION REQUIRED\n`;
    md += `- **Volatility Index:** ${volatility}/100\n`;
    if (briefing.actionRequired) {
      md += `- **Recommended Action:** ${briefing.actionRequired}\n`;
    }
    md += `\n`;

    md += `## 2. EXECUTIVE SUMMARY & VERIFIED STATUS\n`;
    md += `${briefing.coreStatus}\n\n`;

    if (Array.isArray(briefing.deadlines) && briefing.deadlines.length > 0) {
      md += `## 3. KEY DEADLINES & MILESTONES\n`;
      briefing.deadlines.forEach((dl) => {
        md += `- **[${dl.urgency || 'KEY DATE'}] ${dl.title}:** ${dl.date}\n`;
      });
      md += `\n`;
    }

    if (Array.isArray(briefing.keyPoints) && briefing.keyPoints.length > 0) {
      md += `## 4. VERIFIED INTELLIGENCE HIGHLIGHTS\n`;
      briefing.keyPoints.forEach((kp) => {
        md += `- **[${kp.badge}]** ${kp.text}\n`;
      });
      md += `\n`;
    }

    if (Array.isArray(diffs) && diffs.length > 0) {
      md += `## 5. CHRONOLOGICAL CHANGE AUDIT TRAIL\n`;
      diffs.slice(0, 5).forEach((d) => {
        const dDate = new Date(d.detectedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
        md += `### Change Recorded: ${dDate}\n`;
        md += `${d.summary}\n`;
        if (d.sourceUrls?.length) {
          md += `*Sources:* ${d.sourceUrls.join(', ')}\n\n`;
        }
      });
    }

    if (briefing.bulletins?.length) {
      md += `## 6. PRIMARY CITATIONS & MEDIA SOURCES\n`;
      briefing.bulletins.forEach((b) => {
        md += `- [${b.type}] ${b.title} (${b.source}) - ${b.link}\n`;
      });
      md += `\n`;
    }

    md += `---\n*Generated by Notice Me Autonomous Web Intelligence Radar*\n`;
    return md;
  }

  async function handleCopyMarkdown() {
    try {
      const md = generateMarkdown();
      await navigator.clipboard.writeText(md);
      setCopyStatus('markdown');
      setTimeout(() => setCopyStatus(''), 2500);
    } catch {
      setCopyStatus('error');
    }
  }

  async function handleCopyShareLink() {
    try {
      const url = new URL(window.location.href);
      url.searchParams.set('dossier', 'open');
      await navigator.clipboard.writeText(url.toString());
      setCopyStatus('link');
      setTimeout(() => setCopyStatus(''), 2500);
    } catch {
      setCopyStatus('error');
    }
  }

  return createPortal(
    <div className="dossier-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="dossier-modal-container" role="dialog" aria-modal="true" aria-labelledby="dossier-title">
        {/* Screen Toolbar (hidden in print) */}
        <div className="dossier-toolbar no-print">
          <div className="dossier-toolbar-title">
            <IconShield size={16} style={{ color: 'var(--brand-primary)' }} />
            <span>EXECUTIVE INTELLIGENCE DOSSIER</span>
          </div>
          <div className="dossier-toolbar-actions">
            <button
              type="button"
              className="button button-quiet dossier-action-btn"
              onClick={handleCopyShareLink}
              title="Copy shareable URL to clipboard"
            >
              {copyStatus === 'link' ? <IconCheck size={13} /> : <IconExternalLink size={13} />}
              <span>{copyStatus === 'link' ? 'Link Copied' : 'Share Link'}</span>
            </button>
            <button
              type="button"
              className="button button-quiet dossier-action-btn"
              onClick={handleCopyMarkdown}
              title="Copy formatted markdown report"
            >
              {copyStatus === 'markdown' ? <IconCheck size={13} /> : <IconCopy size={13} />}
              <span>{copyStatus === 'markdown' ? 'Copied MD' : 'Copy Markdown'}</span>
            </button>
            <button
              type="button"
              className="button button-primary dossier-action-btn"
              onClick={handlePrint}
              title="Print document or save as PDF"
            >
              <IconPrinter size={14} />
              <span>Print / Save PDF</span>
            </button>
            <button
              type="button"
              className="dossier-close-button"
              onClick={onClose}
              aria-label="Close dossier"
            >
              <IconX size={16} />
            </button>
          </div>
        </div>

        {/* Printable & Exportable Dossier Sheet */}
        <div className="dossier-paper" id="dossier-print-root">
          <header className="dossier-header">
            <div className="dossier-header-top">
              <div className="dossier-brand-row">
                <IconShield size={24} style={{ color: 'var(--brand-primary)' }} />
                <div>
                  <div className="dossier-org">NOTICE ME INTELLIGENCE SYSTEM</div>
                  <div className="dossier-classification">AUTONOMOUS RADAR • VERIFIED CHANGE AUDIT</div>
                </div>
              </div>
              <div className="dossier-meta-badge">
                <span>REF #{topic.id.slice(0, 8).toUpperCase()}</span>
                <span className="dossier-date">{nowStr}</span>
              </div>
            </div>

            <div className="dossier-subject-block">
              <span className="dossier-category-pill">{(topic.category || 'General Notice').toUpperCase()}</span>
              <h1 id="dossier-title" className="dossier-subject-title">{topic.name}</h1>
              <p className="dossier-query">
                <span className="dossier-query-label">Monitored Target Query:</span> “{topic.query}”
              </p>
            </div>
          </header>

          {/* Radar Assessment & Volatility Gauge */}
          <section className="dossier-radar-grid">
            <div className="dossier-radar-card">
              <div className="dossier-section-eyebrow">URGENCY CLASSIFICATION</div>
              <div className={`dossier-urgency-banner urgency-${urgency.toLowerCase()}`}>
                <span className="live-dot" style={{ width: '7px', height: '7px' }} />
                <span>{urgency} ACTION REQUIRED</span>
              </div>
            </div>

            <div className="dossier-radar-card">
              <div className="dossier-section-eyebrow">VOLATILITY RADAR INDEX</div>
              <div className="dossier-volatility-display">
                <div className="volatility-score-text">
                  <strong>{volatility}</strong>
                  <span>/ 100</span>
                </div>
                <div className="volatility-meter-track">
                  <div
                    className={`volatility-meter-fill fill-${urgency.toLowerCase()}`}
                    style={{ width: `${volatility}%` }}
                  />
                </div>
              </div>
            </div>
          </section>

          {/* Executive Summary */}
          <section className="dossier-section">
            <h2 className="dossier-section-heading">1. Verified Status Overview</h2>
            <div className="dossier-summary-box">
              <p>{briefing.coreStatus}</p>
              {briefing.primarySource && (
                <div className="dossier-primary-source">
                  <span>Primary Portal Citation: </span>
                  <a href={briefing.primarySource.link} target="_blank" rel="noopener noreferrer">
                    {briefing.primarySource.name} ↗
                  </a>
                </div>
              )}
            </div>
          </section>

          {/* Action Required Callout if present */}
          {briefing.actionRequired && (
            <section className="dossier-section">
              <h2 className="dossier-section-heading">2. Recommended Action</h2>
              <div className="dossier-action-callout">
                <p><strong>Immediate Action: </strong>{briefing.actionRequired}</p>
              </div>
            </section>
          )}

          {/* Key Dates & Deadlines */}
          {Array.isArray(briefing.deadlines) && briefing.deadlines.length > 0 && (
            <section className="dossier-section">
              <h2 className="dossier-section-heading">
                {briefing.actionRequired ? '3. Detected Deadlines & Milestones' : '2. Detected Deadlines & Milestones'}
              </h2>
              <div className="dossier-deadlines-table">
                <div className="table-header-row">
                  <span>Urgency</span>
                  <span>Event / Milestone</span>
                  <span>Scheduled Date</span>
                </div>
                {briefing.deadlines.map((dl, idx) => (
                  <div key={idx} className="table-data-row">
                    <span className={`table-urgency-cell urgency-${(dl.urgency || 'medium').toLowerCase()}`}>
                      {dl.urgency || 'KEY DATE'}
                    </span>
                    <span className="table-event-cell">{dl.title}</span>
                    <span className="table-date-cell">{dl.date}</span>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* Key Verified Highlights */}
          {Array.isArray(briefing.keyPoints) && briefing.keyPoints.length > 0 && (
            <section className="dossier-section">
              <h2 className="dossier-section-heading">Key Verified Highlights</h2>
              <ul className="dossier-highlights-list">
                {briefing.keyPoints.map((kp, idx) => (
                  <li key={idx}>
                    <span className="dossier-badge-pill">{kp.badge}</span>
                    <span className="dossier-highlight-text">{kp.text}</span>
                  </li>
                ))}
              </ul>
            </section>
          )}

          {/* Recent Chronological Changes */}
          {Array.isArray(diffs) && diffs.length > 0 && (
            <section className="dossier-section">
              <h2 className="dossier-section-heading">Chronological Change Audit Trail</h2>
              <div className="dossier-diffs-timeline">
                {diffs.slice(0, 5).map((d) => {
                  const dDate = new Date(d.detectedAt).toLocaleDateString('en-US', {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                  });
                  return (
                    <div key={d.id} className="dossier-diff-item">
                      <div className="dossier-diff-meta">
                        <span className="dossier-diff-date">{dDate}</span>
                        {d.structured?.impact && (
                          <span className={`dossier-diff-impact impact-${d.structured.impact.toLowerCase()}`}>
                            {d.structured.impact}
                          </span>
                        )}
                      </div>
                      <div className="dossier-diff-summary">
                        <strong>{d.structured?.headline || d.summary?.split('\n')[0] || 'Update Detected'}</strong>
                        <p>{d.structured?.explanation || d.summary}</p>
                      </div>
                      {d.sourceUrls?.length > 0 && (
                        <div className="dossier-diff-sources">
                          <span>Evidence: </span>
                          {d.sourceUrls.slice(0, 2).map((url, uidx) => {
                            let domain = 'source';
                            try { domain = new URL(url).hostname.replace(/^www\./, ''); } catch {}
                            return (
                              <a key={uidx} href={url} target="_blank" rel="noopener noreferrer">
                                {domain}
                              </a>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </section>
          )}

          {/* Citations & Media Bulletins */}
          {briefing.bulletins?.length > 0 && (
            <section className="dossier-section">
              <h2 className="dossier-section-heading">Citations & Primary Evidence</h2>
              <div className="dossier-sources-grid">
                {briefing.bulletins.map((b, idx) => (
                  <div key={idx} className="dossier-source-card">
                    <div className="dossier-source-card-top">
                      <span className="dossier-source-type">{b.type}</span>
                      {b.date && <span className="dossier-source-date">{b.date}</span>}
                    </div>
                    <div className="dossier-source-title">{b.title}</div>
                    <div className="dossier-source-footer">
                      <span>{b.source}</span>
                      <a href={b.link} target="_blank" rel="noopener noreferrer">
                        Verify Record ↗
                      </a>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* Dossier Footer / Authenticity Seal */}
          <footer className="dossier-footer">
            <div className="dossier-seal-block">
              <div className="seal-line">OFFICIAL RECORD MEMO • AUTONOMOUS INTELLIGENCE BRIEFING</div>
              <div className="seal-sub">Verified against official Google Search and News records via SerpApi + Gemini.</div>
            </div>
            <div className="dossier-page-meta">
              <span>Notice Me Document ID: {topic.id}</span>
              <span>Generated: {nowStr}</span>
            </div>
          </footer>
        </div>
      </div>
    </div>,
    document.body
  );
}
