import React, { useState } from 'react';
import { createPortal } from 'react-dom';

export default function DossierModal({ topic, briefing, diffs = [], onClose }) {
  const [copyStatus, setCopyStatus] = useState('');

  if (!topic || !briefing) return null;

  const volatility = briefing.volatilityScore ?? (briefing.urgency === 'CRITICAL' ? 85 : briefing.urgency === 'MODERATE' ? 55 : 25);
  const urgency = briefing.urgency || (volatility >= 75 ? 'CRITICAL' : volatility >= 45 ? 'MODERATE' : 'ROUTINE');
  const nowStr = new Date().toLocaleString('en-US', {
    dateStyle: 'full',
    timeStyle: 'short',
  });

  function handlePrint() {
    window.print();
  }

  function generateMarkdown() {
    let md = `# EXECUTIVE INTELLIGENCE DOSSIER\n`;
    md += `**Subject:** ${topic.name}\n`;
    md += `**Category:** ${(topic.category || 'General Notice').toUpperCase()} | **Ref ID:** ${topic.id}\n`;
    md += `**Query:** \`${topic.query}\`\n`;
    md += `**Generated:** ${nowStr}\n`;
    md += `**Classification:** AUTONOMOUS VERIFIED RADAR (SERPAPI + GEMINI AI)\n\n`;
    md += `---\n\n`;

    md += `## 1. RADAR METRICS & URGENCY ASSESSMENT\n`;
    md += `- **Urgency Status:** ${urgency} ACTION REQUIRED\n`;
    md += `- **Volatility Index:** ${volatility}/100\n`;
    if (briefing.actionRequired) {
      md += `- **Recommended Action:** ${briefing.actionRequired}\n`;
    }
    md += `\n`;

    md += `## 2. EXECUTIVE SUMMARY & VERIFIED STATUS\n`;
    md += `${briefing.coreStatus}\n\n`;

    if (Array.isArray(briefing.deadlines) && briefing.deadlines.length > 0) {
      md += `## 3. KEY DEADLINES & MILESTONES\n`;
      briefing.deadlines.forEach((dl) => {
        md += `- **[${dl.urgency || 'KEY DATE'}] ${dl.title}:** ${dl.date}\n`;
      });
      md += `\n`;
    }

    if (Array.isArray(briefing.keyPoints) && briefing.keyPoints.length > 0) {
      md += `## 4. VERIFIED INTELLIGENCE HIGHLIGHTS\n`;
      briefing.keyPoints.forEach((kp) => {
        md += `- **[${kp.badge}]** ${kp.text}\n`;
      });
      md += `\n`;
    }

    if (Array.isArray(diffs) && diffs.length > 0) {
      md += `## 5. CHRONOLOGICAL CHANGE AUDIT TRAIL\n`;
      diffs.slice(0, 5).forEach((d) => {
        const dDate = new Date(d.detectedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
        md += `### Change Recorded: ${dDate}\n`;
        md += `${d.summary}\n`;
        if (d.sourceUrls?.length) {
          md += `*Sources:* ${d.sourceUrls.join(', ')}\n\n`;
        }
      });
    }

    if (briefing.bulletins?.length) {
      md += `## 6. PRIMARY CITATIONS & MEDIA SOURCES\n`;
      briefing.bulletins.forEach((b) => {
        md += `- [${b.type}] ${b.title} (${b.source}) - ${b.link}\n`;
      });
      md += `\n`;
    }

    md += `---\n*Generated by Notice Me Autonomous Web Intelligence Radar*\n`;
    return md;
  }

  async function handleCopyMarkdown() {
    try {
      const md = generateMarkdown();
      await navigator.clipboard.writeText(md);
      setCopyStatus('markdown');
      setTimeout(() => setCopyStatus(''), 2500);
    } catch {
      setCopyStatus('error');
    }
  }

  async function handleCopyShareLink() {
    try {
      const url = new URL(window.location.href);
      url.searchParams.set('dossier', 'open');
      await navigator.clipboard.writeText(url.toString());
      setCopyStatus('link');
      setTimeout(() => setCopyStatus(''), 2500);
    } catch {
      setCopyStatus('error');
    }
  }

  return createPortal(
    <div className="dossier-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="dossier-modal-container" role="dialog" aria-modal="true" aria-labelledby="dossier-title">
        {/* Screen Toolbar (hidden in print) */}
        <div className="dossier-toolbar no-print">
          <div className="dossier-toolbar-title">
            <span className="dossier-emblem">✳</span>
            <span>EXECUTIVE INTELLIGENCE DOSSIER</span>
          </div>
          <div className="dossier-toolbar-actions">
            <button
              type="button"
              className="button button-quiet dossier-action-btn"
              onClick={handleCopyShareLink}
              title="Copy shareable URL to clipboard"
            >
              {copyStatus === 'link' ? '✓ Link Copied' : '🔗 Copy Link'}
            </button>
            <button
              type="button"
              className="button button-quiet dossier-action-btn"
              onClick={handleCopyMarkdown}
              title="Copy formatted markdown report"
            >
              {copyStatus === 'markdown' ? '✓ Copied Markdown' : '📋 Copy Markdown'}
            </button>
            <button
              type="button"
              className="button button-primary dossier-action-btn"
              onClick={handlePrint}
              title="Print document or save as PDF"
            >
              🖨️ Print / Save PDF
            </button>
            <button
              type="button"
              className="dossier-close-button"
              onClick={onClose}
              aria-label="Close dossier"
            >
              ✕
            </button>
          </div>
        </div>

        {/* Printable & Exportable Dossier Sheet */}
        <div className="dossier-paper" id="dossier-print-root">
          <header className="dossier-header">
            <div className="dossier-header-top">
              <div className="dossier-brand-row">
                <span className="dossier-watermark-symbol">✳</span>
                <div>
                  <div className="dossier-org">NOTICE ME INTELLIGENCE SYSTEM</div>
                  <div className="dossier-classification">AUTONOMOUS RADAR • VERIFIED CRYPTO AUDIT</div>
                </div>
              </div>
              <div className="dossier-meta-badge">
                <span>REF #{topic.id.slice(0, 8).toUpperCase()}</span>
                <span className="dossier-date">{nowStr}</span>
              </div>
            </div>

            <div className="dossier-subject-block">
              <span className="dossier-category-pill">{(topic.category || 'General Notice').toUpperCase()}</span>
              <h1 id="dossier-title" className="dossier-subject-title">{topic.name}</h1>
              <p className="dossier-query">
                <span className="dossier-query-label">Monitored Target Query:</span> “{topic.query}”
              </p>
            </div>
          </header>

          {/* Radar Assessment & Volatility Gauge */}
          <section className="dossier-radar-grid">
            <div className="dossier-radar-card">
              <div className="dossier-section-eyebrow">URGENCY CLASSIFICATION</div>
              <div className={`dossier-urgency-banner urgency-${urgency.toLowerCase()}`}>
                <span className="urgency-beacon" />
                <span>{urgency} ACTION REQUIRED</span>
              </div>
            </div>

            <div className="dossier-radar-card">
              <div className="dossier-section-eyebrow">VOLATILITY RADAR INDEX</div>
              <div className="dossier-volatility-display">
                <div className="volatility-score-text">
                  <strong>{volatility}</strong>
                  <span>/ 100</span>
                </div>
                <div className="volatility-meter-track">
                  <div
                    className={`volatility-meter-fill fill-${urgency.toLowerCase()}`}
                    style={{ width: `${volatility}%` }}
                  />
                </div>
              </div>
            </div>
          </section>

          {/* Action Required Callout if present */}
          {briefing.actionRequired && (
            <div className="dossier-action-banner">
              <div className="dossier-action-label">⚡ DIRECT ACTION DIRECTIVE</div>
              <p className="dossier-action-text">{briefing.actionRequired}</p>
            </div>
          )}

          {/* Executive Verified Status */}
          <section className="dossier-section">
            <div className="dossier-section-heading">
              <span className="section-num">01</span>
              <h2>CURRENT VERIFIED EXECUTIVE STATUS</h2>
            </div>
            <div className="dossier-summary-content">
              <p>{briefing.coreStatus}</p>
            </div>
          </section>

          {/* Detected Deadlines & Milestones */}
          {Array.isArray(briefing.deadlines) && briefing.deadlines.length > 0 && (
            <section className="dossier-section">
              <div className="dossier-section-heading">
                <span className="section-num">02</span>
                <h2>IMPENDING DEADLINES & MILESTONES</h2>
              </div>
              <div className="dossier-table-wrap">
                <table className="dossier-table">
                  <thead>
                    <tr>
                      <th>URGENCY</th>
                      <th>MILESTONE EVENT</th>
                      <th>VERIFIED DATE</th>
                    </tr>
                  </thead>
                  <tbody>
                    {briefing.deadlines.map((dl, idx) => (
                      <tr key={idx}>
                        <td>
                          <span className={`table-urgency-pill pill-${(dl.urgency || 'medium').toLowerCase()}`}>
                            {dl.urgency || 'KEY DATE'}
                          </span>
                        </td>
                        <td><strong>{dl.title}</strong></td>
                        <td><code>{dl.date}</code></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>
          )}

          {/* Key Verified Highlights */}
          {Array.isArray(briefing.keyPoints) && briefing.keyPoints.length > 0 && (
            <section className="dossier-section">
              <div className="dossier-section-heading">
                <span className="section-num">03</span>
                <h2>KEY INTELLIGENCE HIGHLIGHTS</h2>
              </div>
              <ul className="dossier-highlights-list">
                {briefing.keyPoints.map((pt, idx) => (
                  <li key={idx} className="dossier-highlight-item">
                    <span className="dossier-item-badge">{pt.badge}</span>
                    <span className="dossier-item-text">{pt.text}</span>
                  </li>
                ))}
              </ul>
            </section>
          )}

          {/* Chronological Audit Trail (Diffs) */}
          {Array.isArray(diffs) && diffs.length > 0 && (
            <section className="dossier-section page-break-before">
              <div className="dossier-section-heading">
                <span className="section-num">04</span>
                <h2>CHRONOLOGICAL CHANGE AUDIT TRAIL</h2>
              </div>
              <div className="dossier-audit-timeline">
                {diffs.slice(0, 5).map((d) => {
                  const dDate = new Date(d.detectedAt).toLocaleDateString('en-US', {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit',
                  });
                  return (
                    <div key={d.id} className="dossier-audit-card">
                      <div className="audit-card-meta">
                        <span className="audit-card-date">{dDate}</span>
                        <span className="audit-card-badge">VERIFIED DELTA</span>
                      </div>
                      <div className="audit-card-summary">{d.summary}</div>
                    </div>
                  );
                })}
              </div>
            </section>
          )}

          {/* Citations and Sources */}
          {Array.isArray(briefing.bulletins) && briefing.bulletins.length > 0 && (
            <section className="dossier-section">
              <div className="dossier-section-heading">
                <span className="section-num">05</span>
                <h2>PRIMARY CITATIONS & DISPATCH SOURCES</h2>
              </div>
              <div className="dossier-citations-list">
                {briefing.bulletins.map((b, idx) => (
                  <div key={idx} className="citation-entry">
                    <span className="citation-num">[{idx + 1}]</span>
                    <div className="citation-body">
                      <strong>{b.title}</strong>
                      <div className="citation-meta">
                        <span>{b.source}</span>
                        {b.date && <span>• {b.date}</span>}
                        <a href={b.link} target="_blank" rel="noopener noreferrer" className="citation-link">
                          {b.link}
                        </a>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* Official Verification Footer */}
          <footer className="dossier-footer">
            <div className="dossier-footer-left">
              <span className="dossier-footer-stamp">NOTICE ME RADAR • OFFICIAL INTEL</span>
              <p>Autonomous monitoring powered by SerpApi Google Search & News with Google Gemini AI synthesis.</p>
            </div>
            <div className="dossier-footer-right">
              <div className="dossier-hash">INTEGRITY ID: {topic.id}</div>
              <div className="dossier-hash-date">STAMPED {new Date().toISOString()}</div>
            </div>
          </footer>
        </div>
      </div>
    </div>,
    document.body
  );
}
